# Generated by Django 2.0.3 on 2020-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscriberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('addedTimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
