# Generated by Django 2.0.3 on 2020-03-23 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seeCOVID19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberlist',
            name='addedTimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
